.TH "TEMPMAIL" "" "May 2014" "" ""
.SH "NAME"
\fBtempmail\fR \- Easily create temporary emails and fetch their inbox
.SH SYNOPSIS
.P
tempmail <provider> [emailAddress]
.SH DESCRIPTION
.RS 0
.IP \(bu 2
Specifying only a provider will create a new temporary email address\.
.IP \(bu 2
Specifying a provider + email will return the inbox (in JSON format)\.

.RE
.SH AUTHORS
.P
Trevor Senior trevor@tsenior\.com
.SH BUGS
.P
https://github\.com/trevorsenior/sonare/issues

